// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_H6GHhfbXumNOlVx6xEtxkvtoUS90nNY',
    appId: '1:995077700115:web:4e784ed696468477ad5de6',
    messagingSenderId: '995077700115',
    projectId: 'training-iti-b9127',
    authDomain: 'training-iti-b9127.firebaseapp.com',
    storageBucket: 'training-iti-b9127.appspot.com',
    measurementId: 'G-89QLWWE63G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Vr0muneT5dizikTC-25GtVuwFgAWdvw',
    appId: '1:995077700115:android:841e0f747190e48cad5de6',
    messagingSenderId: '995077700115',
    projectId: 'training-iti-b9127',
    storageBucket: 'training-iti-b9127.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA-mpyywum0VGCnQEOH_r_XiEJlzzqBHE',
    appId: '1:995077700115:ios:9cce7cd1b4b06552ad5de6',
    messagingSenderId: '995077700115',
    projectId: 'training-iti-b9127',
    storageBucket: 'training-iti-b9127.appspot.com',
    iosClientId: '995077700115-jnjl3eh63rnssls7hld4de0vjodlv1pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
